app = "csharp-practicum"
primary_region = "fra"

[build]
  [build.args]
    GO_VERSION = "1.21"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [[services.tcp_checks]]
    interval = 15000
    timeout = 2000
    grace_period = 30000

[[services]]
  protocol = "tcp"
  internal_port = 5173

  [[services.ports]]
    port = 5173